export enum genre {
  Fiction = 'Fiction',
  NonFiction = 'Non-fiction',
  Mystery = 'Mystery',
  Fantasy = 'Fantasy',
  ScienceFiction = 'Science Fiction',
  HistoricalFiction = 'Historical Fiction',
  Romance = 'Romance',
  Thriller = 'Thriller',
  Horror = 'Horror',
  Biography = 'Biography',
  SelfHelp = 'Self-help',
  Poetry = 'Poetry',
  Adventure = 'Adventure',
}
